[package]
name = "katalog-lib"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
katalog-lib-reflect.workspace = true
katalog-lib-traits.workspace = true

[lints]
workspace = true
